# Should be self evident.
#
# terraform probably preserved in aspic now.
# @see ../updatecli.d/sdk-*.yml
terraform:
  version: 1.6.6
opentofu:
  version: 1.10.7
sdkman:
  java: 21.0.9-amzn
  gradle: 9.2.1
  maven: 3.9.11
  jbang: 0.134.2
rvm:
  ruby: 3.4.7
nvm:
  version: v0.40.3
golang:
  version: 1.25.4
sonar-scanner:
  version: 7.3.0.5189
python:
  version: 3.14.0
amazon-ecr-credential-helper:
  version: 0.11.0
