# Should be self evident.
#
# terraform probably preserved in aspic now.
# @see ../updatecli.d/sdk-*.yml
terraform:
  version: 1.6.6
opentofu:
  version: 1.11.4
sdkman:
  java: 21.0.9-amzn
  gradle: 9.3.1
  maven: 3.9.12
  jbang: 0.135.1
rvm:
  ruby: 3.4.8
nvm:
  version: v0.40.4
golang:
  version: 1.25.6
sonar-scanner:
  version: 8.0.1.6346
python:
  version: 3.14.2
amazon-ecr-credential-helper:
  version: 0.11.0
